"$schema" = "https://starship.rs/config-schema.json"

format = """
$username\
$hostname\
$shell\
${custom.incognito}\
$directory\
$git_branch\
$git_state\
$git_status\
$line_break\
$character\
"""

right_format = "$all"

[package]
disabled = true

[directory]
style = "bold blue"

[custom.incognito]
when = 'printenv INCOGNITO'
symbol = '👁 '
style = 'fg:purple bold'
format = '[$symbol ]($style)'

[shell]
disabled = false
style = "bold red"
bash_indicator = " bash"
zsh_indicator = " zsh"
fish_indicator = "🐟 fish"
powershell_indicator = " pwsh"
nu_indicator = "󰎖 nu"
cmd_indicator = "📟 cmd"
